# Generated by Django 4.0.6 on 2022-08-05 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projectRUN', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permisos',
        ),
    ]
