# Generated by Django 4.0.6 on 2022-08-05 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectRUN', '0002_delete_permisos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id_permiso', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_permiso', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
