# Generated by Django 4.0.6 on 2022-08-11 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectRUN', '0003_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='intermedia',
            field=models.ManyToManyField(blank=True, to='projectRUN.roles'),
        ),
    ]
