# Generated by Django 4.0.6 on 2022-08-12 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectRUN', '0004_permisos_intermedia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=100)),
                ('apellido_cliente', models.CharField(max_length=100)),
                ('celular_cliente', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(default='2000-01-01')),
                ('direccion', models.CharField(max_length=125)),
            ],
        ),
        migrations.CreateModel(
            name='Envios',
            fields=[
                ('id_envios', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_envio', models.DateField(default='2000-01-01')),
                ('direccion_envio', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MediosDePagos',
            fields=[
                ('id_medio_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_medio_pago', models.CharField(max_length=50)),
                ('estado_medio_pago', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedido', models.IntegerField(primary_key=True, serialize=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.clientes')),
            ],
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='intermedia',
        ),
        migrations.AlterField(
            model_name='marcas',
            name='nombre_marca',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(default='2000-01-01')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.envios')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_correo', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=14)),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.roles')),
            ],
        ),
        migrations.CreateModel(
            name='RolesPermisos',
            fields=[
                ('id_roles_permisos', models.IntegerField(primary_key=True, serialize=False)),
                ('permisos', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.permisos')),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.roles')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.marcas')),
            ],
        ),
        migrations.CreateModel(
            name='PedidosProductos',
            fields=[
                ('id_pedidos_productos', models.IntegerField(primary_key=True, serialize=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.pedidos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha_pagos', models.DateTimeField(auto_now=True)),
                ('medio_pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.mediosdepagos')),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empleado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_empleado', models.CharField(max_length=100)),
                ('apellido_empleado', models.CharField(max_length=100)),
                ('celular_empleado', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(default='2000-01-01')),
                ('eps', models.CharField(max_length=50)),
                ('correo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='clientes',
            name='correo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.usuarios'),
        ),
    ]
