# Generated by Django 4.0.6 on 2022-08-12 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projectRUN', '0005_clientes_envios_mediosdepagos_pedidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id_historial', models.IntegerField(primary_key=True, serialize=False)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.pagos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='projectRUN.ventas')),
            ],
        ),
    ]
